inhibit_all_warnings!
use_frameworks!

abstract_target 'Common' do
	pod 'Quick', '~> 2.0'
	pod 'Nimble', '~> 8.0'

	target 'FueledUtilsTests' do
		platform :ios, '13.0'

		pod 'FueledUtils/ReactiveCombineBridge', path: '../'
		pod 'FueledUtils/CombineOperators', path: '../'
	end
end
